### PR TITLE
Update hardware spec

### PR DESCRIPTION
**Pull request by haslinghuis**
Adding rules:

image

### CODE REVIEW

**Comment by SupaflyFPV** [comment]
Have a few comments from Steve to add bear with me...

**Review by SupaflyFPV — APPROVED** [review]

**Comment by sugaarK** [comment]
@SupaflyFPV  what did Steve have to say

**Review by sugaarK — DISMISSED** [review]

**Comment by SupaflyFPV** [comment]
> @SupaflyFPV what did Steve have to say

"To achieve rule 1 you should use a ground plane. Be very careful splitting that plane by running tracks on the same layer especially near the gyro as that will cause noise."

He also shared a link about ground planes and I thought I should properly absorb it before committing to this guide...

https://www.nwengineeringllc.com/article/should-you-split-ground-planes-in-mixed-signal-pcb-design.php

**Comment by sugaarK** [comment]
Good stuff thanks @SupaflyFPV

**Comment by haslinghuis** [comment]
Should I add a note

**Comment by SupaflyFPV** [comment]
> Should I add a note

My feeling is its too complex an area to insert as a note and I'd rather not risk bad guidance at this stage...I think we can work on it later...

**Comment by haslinghuis** [comment]
image

**Comment by haslinghuis** [comment]
Ok removed
```
To achieve the first rule you should use a ground plane. Be very careful splitting that plane by running tracks on the same layer especially near the gyro as that will cause noise. [reference](https://www.nwengineeringllc.com/article/should-you-split-ground-planes-in-mixed-signal-pcb-design.php)<br /><br />


```

**Review by SupaflyFPV — APPROVED** [review]

**Review by blckmn — APPROVED** [review]

**Pull request merged**
