### PR TITLE
Removing pilots, and members. 

### PR DESCRIPTION
**Pull request by blckmn**
Will look for alternative source for pilot details.

### CODE REVIEW

**Comment by blckmn** [comment]
Moved the members to feed off Github, and the pilots needs a source of data - which will need to be sorted at some point.

**Comment by McGiverGim** [comment]
@blckmn I see that you removed the pilots content, but I see the link at the top bar:

image

Is that expected?

**Comment by mikeller** [comment]
@McGiverGim: I wonder if we are having regional synch issues again. I can still see the content for 'Pilots':

image

**Comment by McGiverGim** [comment]
😆 

It seems... I don't see the Featured pilots content...

**Pull request merged**
