### PR TITLE
move F3 and F1 boards to archive, small mods to some others

### PR DESCRIPTION
**Pull request by ctzsnooze**
boards list contained many old and unsupported boards.
moved F3 and F1 boards to a `boards/archive` directory.
Added a pointer to the betaflight configs directory

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
```
Compiled with problems:
ERROR in ./docs/wiki/boards/archive/CRAZYBEEF3FR.md
Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
Error: MDX compilation failed for file "/home/REDACTED/SYNC/nerdCopter-GIT/betaflight.com/docs/wiki/boards/archive/CRAZYBEEF3FR.md"
Cause: Image static/img/boards/crazybeef3/crazyBeeF3FRbottom.jpg used in docs/wiki/boards/archive/CRAZYBEEF3FR.md not found.
Details:
Error: Image static/img/boards/crazybeef3/crazyBeeF3FRbottom.jpg used in docs/wiki/boards/archive/CRAZYBEEF3FR.md not found.
    at getImageAbsolutePath (/home/REDACTED/SYNC/nerdCopter-GIT/betaflight.com/node_modules/@docusaurus/mdx-loader/lib/remark/transformImage/index.js:98:19)
    at async processImageNode (/home/REDACTED/SYNC/nerdCopter-GIT/betaflight.com/node_modules/@docusaurus/mdx-loader/lib/remark/transformImage/index.js:125:23)
    at async Promise.all (index 1)
    at async /home/REDACTED/SYNC/nerdCopter-GIT/betaflight.com/node_modules/@docusaurus/mdx-loader/lib/remark/transformImage/index.js:138:9
    at Object.mdxLoader (/home/REDACTED/SYNC/nerdCopter-GIT/betaflight.com/node_modules/@docusaurus/mdx-loader/lib/loader.js:126:25)
```

**Review by blckmn — APPROVED** [review]

**Comment by haslinghuis** [comment]
Just a remark. We need targets capitalized as the target is retrieved and shown in firmware_flasher tab. This won't apply to F1 and F3 though.

Linking the img seems to be wrong

image

**Comment by nerdCopter** [comment]
`Image docs/wiki/boards/archive/images/CrazyBeeF3FRtop.jpg used in docs/wiki/boards/archive/CRAZYBEEF3FR.md not found.
`
& 
`Image docs/wiki/boards/archive/images/CrazyBeeF3FStop.jpg used in docs/wiki/boards/archive/CRAZYBEEF3FS.md not found.`

**Comment by ctzsnooze** [comment]
@haslinghuis could you clarify what you mean by the comment above, "We need targets capitalized as the target is retrieved and shown in firmware_flasher tab"?

Do you mean that the file name must match the name of the config file for the board, or that a link in the form `https://betaflight.com/docs/wiki/boards/CONFIG_NAME` should always work?

In docusaurus the link will be set by the text of the H1 line unless otherwise explicitly set as an ID; the file name will not be the link name.

What do you want us to do here, from the point of view of the firmware flasher tab?

**Comment by haslinghuis** [comment]
Wiki button here points to target name on betaflight.com which is in capitals

image

**Comment by haslinghuis** [comment]
Would like to have boards under manufacturers - where we could have manufacturer/board/TARGET

**Comment by ctzsnooze** [comment]
Again, what exactly do you mean?
Do you mean that we need a link from Configurator that must resolve to an information document in betaflight.com with a link that has a matching name?

**Comment by haslinghuis** [comment]
No we use a link in configurator to point where the TARGET is located.

If not present we get https://betaflight.com/docs/wiki/boards/missing

If I would use the full KAKUTEH7 I would get https://betaflight.com/docs/wiki/boards/KAKUTEH7

The proposal to move them to manufacturers was done on discord before. Or at least have manufactorer/board/TARGET. But this is outside of the scope of the change description.

**Comment by ctzsnooze** [comment]
OK I can make the changes needed here to match target names.
so that, for example, https://betaflight.com/docs/wiki/boards/KAKUTEH7 will work.

**Comment by ctzsnooze** [comment]
@haslinghuis @nerdCopter I've fixed the image links and done more tidying up.
All links now have the correct board name.

**Comment by nerdCopter** [comment]
- looks good as designed/intended.
image

- is there a way to have `/docs/wiki/boards/archive` show as a webpage, or is that too complicated?
image

**Comment by haslinghuis** [comment]
Alternative we could have an Archive menu in the wiki root for all archived documents to have everything in one place.

- Release Notes (old)
- Tuning Notes (old)
- Guides (old)
- Boards (old)

**Comment by ctzsnooze** [comment]
It's sufficiently complicated that it's too much for this PR.

In the most recent commit I made it so that the archive directory is named `archived-boards` and it will always appear at the bottom.
The complication is that if you look at the URL in your browser, file listings like these are all given links in the form `/docs/category/boards`.  After the re-naming of the 'archive' for 'boards' to `archived-boards`, it's URL is in the form `/docs/category/archived-boards`.  This is OK I think, for now.

We could indeed move all 'archives' to an 'archive' location but I think that should be a separate PR.

**Review by nerdCopter — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
