### PR TITLE
Update mode tab with categories and new modes

### PR DESCRIPTION
**Pull request by HThuren**
Update missing modes
Mention categories 
Depend of https://github.com/betaflight/betaflight-configurator/pull/3583

### CODE REVIEW

**Review by ctzsnooze — APPROVED** [review]

**Review by VitroidFPV — APPROVED** [review]

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
why merged if some verbiage depends on unmerged #3583 ?

**Comment by haslinghuis** [comment]
> The Category arrange modes in groups, at Cloud build only groups defined in builded firmware are enabled. At local build all groups are enabled.

Guess you mean this part - yes was thinking about it. Cleanup PR upcoming.

**Comment by HThuren** [comment]
> > The Category arrange modes in groups, at Cloud build only groups defined in builded firmware are enabled. At local build all groups are enabled.
> 
> Guess you mean this part - yes was thinking about it. Cleanup PR upcoming.
> 
> #319

@nerdCopter @haslinghuis, argh, I belived Depend of https://github.com/betaflight/betaflight-configurator/pull/3583 was the way to wait for merge. Another time, how do you want this,to avoid need or cleanup ?

**Comment by haslinghuis** [comment]
@HThuren No worries - my mistake - only saw after merge. Did the cleanup already. The rest of the PR is good to have included.

**Pull request merged**
