### PR TITLE
Improving Betaflight logo resolution

### PR DESCRIPTION
**Pull request by Asizon**
Deleted old png logo and added new svg big resolution logo from Betaflight Configurator repository:

image

### CODE REVIEW

**Comment by mikeller** [comment]
Good find!

**Review by blckmn — APPROVED** [review]

**Comment by Asizon** [comment]
Sorry, I have push a logo position fix for smartphone view.

**Review by blckmn — APPROVED** [review]

**Review by mikeller — APPROVED** [review]

**Comment by Asizon** [comment]
Is weird, I dont know why but Css changes are note correcty uploaded...

image

**Comment by Asizon** [comment]
nah it just a local cache problem, thanks @fgiudice98 for the tip

**Pull request merged**
