### PR TITLE
Add Lint Target to Makefile

### PR DESCRIPTION
**Pull request by edenreich**
## Summary

Added a .astylerc config file to the codebase repo.

### CODE REVIEW

**Comment by haslinghuis** [comment]
Depends on https://github.com/betaflight/betaflight/pull/13744 for implementation.

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
i
m just concerned with someone doing this as part of their PR.
```
git diff --name-only | wc
    523     523   17395
```

**Comment by haslinghuis** [comment]
PR is based on master :(

**Review by haslinghuis — CHANGES_REQUESTED** [review]
Requires new PR as this is based on master.

**Pull request closed without merging**
