### PR TITLE
Fix build errors

### PR DESCRIPTION
**Pull request by haslinghuis**
:crossed_fingers:

### CODE REVIEW

**Comment by haslinghuis** [comment]
Funny, did not rename this:

image

**Comment by haslinghuis** [comment]
@freasy can we fix this please

**Comment by freasy** [comment]
Okay, both checks returned without an error. So they should pass! I will fix that in another pr.

**Review by freasy — APPROVED** [review]
Fixes the current checks. Even tho they report a failure, they have non inside.

**Review by SupaflyFPV — APPROVED** [review]

**Pull request merged**
