### PR TITLE
full USE_ list

### PR DESCRIPTION
**Pull request by nerdCopter**
EDIT: ctsnooze has found better grep commands and retro fitted into https://github.com/betaflight/betaflight.com/pull/418 and config.h cleanup into https://github.com/betaflight/config/pull/420.
This PR should be closed, but we should retain removal of the `4.4` specificity from the API page. It should also link to his new document `docs/development/Defines.md`

image

https://deploy-preview-419.dev.web.betaflight.com/docs/development/API/Cloud-Build-API#other

### CODE REVIEW

**Comment by nerdCopter** [comment]
- i'm certain too many defines here.
- created via commit `c155f5830	Mark Haslinghuis	2024-04-28	Update EEPROM version for 4.5 (#13498)`

**Comment by haslinghuis** [comment]
Some of these custom defines should go to other options too :)

https://github.com/betaflight/betaflight.com/pull/419/files#diff-17bfd1cf3751acbf94f91e31b5ce492e08dad4aa9ea12ecdee991a699c23f4e8R84-R97

**Comment by nerdCopter** [comment]
Oh, I see, we have `Other Options`, and i added `Other` :zany_face: :man_facepalming:

**Comment by nerdCopter** [comment]
Not certain how to handle.  if i move the spoiler under `Other Options`, such is incorrect as well.
Maybe rename `### Other` to `### Full List`.
and rename spoiler title to  what?

**Comment by haslinghuis** [comment]
```
### Overview

<Full List>
```

**Comment by nerdCopter** [comment]
the only thing i dont like is this is under 4.4, but the list is from 4.5
image

**Comment by nerdCopter** [comment]
updated/fixed. still more defines than usable i believe.

**Comment by haslinghuis** [comment]
Perhaps
- mention RACE PRO was introduced in 4.5
- `OSD_QUICK_MENU`, `RPM LIMIT`, `SPEC_ARM_SCREEN` were added in 4.5
- not checked but `GPS_PLUS_CODES` is probably included automatically when using `USE_GPS`

**Pull request closed without merging**
