### PR TITLE
Add old wiki

### PR DESCRIPTION
**Pull request by haslinghuis**
Todo:

- [x] Add folder structure for old wiki
- [x] Add old wiki into new structure
- [x] Rename board files
- [x] Add images
- [x] Convert image URL
- [x] Move old wiki to old folder
- [x] Add boards to new wiki

### CODE REVIEW

**Comment by haslinghuis** [comment]
Need a script to replace recursive for example: betaflight/bf_logo.png (not all images reside in subfolder)

Before: https://raw.githubusercontent.com/wiki/betaflight/betaflight/images/betaflight/bf_logo.png

After: https://betaflight.com/assets/images/betaflight/bf_logo.png

**Comment by haslinghuis** [comment]
Created new folder structure:

```
Configurator
        All TABs for instant support.

General
	FAQ
	Flying Tips
	Free-style Tuning Principles
	PID Tuning Guide
	Release Notes
	Tuning Notes

Presets
	Presets
	Community Presets

Configuration
	CLI Commands
	Configuration
	Motors & ESC
	Receiver & HID
	Serial Communication
	Video Setup (Camera, VTX & OSD)

Troubleshooting

Tuning
	PID Tuning, Rates & Filters

Autonomous
	GPS

Development
	API
	Parameter Groups

Documentation
	(All documentation from betaflight firmware repo)
	Cloud Build API

Manufacturers
	Custom Board Configuration
	Create a board configuration
	Manufacturer Design Guidelines
	Betaflight certified program
Boards		
	
```

**Comment by haslinghuis** [comment]
Maybe we have a separate documentation section - but we like to consolidate as much as possible.

**Comment by freasy** [comment]
> Need a script to replace recursive for example: `betaflight/bf_logo.png` (not all images reside in subfolder)
> 
> Before: https://raw.githubusercontent.com/wiki/betaflight/betaflight/images/betaflight/bf_logo.png After: https://betaflight.com/assets/img/betaflight/bf_logo.png
> 
> `find . -type f -exec sed -i \ 's/https://raw.githubusercontent.com/wiki/betaflight/betaflight/images_https://betaflight.com/assets/img/g' {} +`
> 
> Need confirmation on the target directory as online we have static/img.
> 
> @freasy please confirm

Confirmed

**Comment by haslinghuis** [comment]
Getting:

sed: -e expression #1, char 12: unknown option to `s'

**Comment by haslinghuis** [comment]
```
find . -type f -exec sed -i 's,https://raw.githubusercontent.com/wiki/betaflight/betaflight/images,https://betaflight.com/assets/img,g' {} +
```

did the trick

**Comment by freasy** [comment]
> Maybe we have a separate documentation section - but we like to consolidate as much as possible.

I would make a "old" directory for the old wiki stuff - so its there, if you need it (and its very good searchable) but it doesnt polute the new structure.

**Comment by blckmn** [comment]
> > Maybe we have a separate documentation section - but we like to consolidate as much as possible.
> 
> I would make a "old" directory for the old wiki stuff - so its there, if you need it (and its very good searchable) but it doesnt polute the new structure.

But attempt to bring across whatever is still relevant and would add value to the main site!

**Comment by haslinghuis** [comment]
Totally agree. But let's start with the migration. After that we can move things in place and start with (consolidating) content.

The question now should we still have wiki separated from documents as traditional.

Rather would have a KB instead of wiki and docs

**Review by SupaflyFPV — APPROVED** [review]
If you want to take it all across first then filter it - lets go

**Pull request merged**
