### PR TITLE
4.5 CLI Reference

### PR DESCRIPTION
**Pull request by nerdCopter**
* moves 4.0 CLI reference to archive.
* adds 4.5 CLI reference to current.
* needs facts checking (i simply copy/pasted `help` and `get` commands with minor alteration, using base `make FOXEERF405` hex).

direct Netlify link https://deploy-preview-431.dev.web.betaflight.com/docs/wiki/guides/current/Betaflight-4.5-CLI-commands

### CODE REVIEW

**Comment by haslinghuis** [comment]
And group by define :rofl: 

Just kidding :)

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
i will have to repair deploy/checks.

**Comment by nerdCopter** [comment]
```
3:22:26 PM: Browserslist: caniuse-lite is outdated. Please run:
3:22:26 PM:   npx update-browserslist-db@latest
3:22:26 PM:   Why you should do it regularly: https://github.com/browserslist/update-db#readme
3:22:26 PM: [info] [webpackbar] Compiling Client
3:22:26 PM: [info] [webpackbar] Compiling Server
3:22:34 PM: [success] [webpackbar] Client: Compiled successfully in 8.18s
3:22:40 PM: SyntaxError: Unexpected token < in JSON at position 0
3:22:40 PM:     at JSON.parse (<anonymous>)
3:22:40 PM:     at parseJSONFromBytes (node:internal/deps/undici/undici:5584:19)
3:22:40 PM:     at successSteps (node:internal/deps/undici/undici:5555:27)
3:22:40 PM:     at fullyReadBody (node:internal/deps/undici/undici:1665:9)
3:22:40 PM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3:22:40 PM:     at async specConsumeBody (node:internal/deps/undici/undici:5564:7)
```
`npx update-browserslist-db@latest` changes `package-lock.json`. Not sure if i should do that in this PR.

**Comment by haslinghuis** [comment]
Separate PR please - and rebase this on that once merged.

**Comment by nerdCopter** [comment]
ready for review. have i missed anything? (did not apply all custom defines, maybe i have missed parameters)

**Review by haslinghuis — APPROVED** [review]

**Review by KarateBrot — APPROVED** [review]

**Pull request merged**
