### PR TITLE
Axis updates

### PR DESCRIPTION
**Pull request by SupaflyFPV**
Adding Axis Sponsorship

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
image

**Review by nerdCopter — DISMISSED** [review]

**Comment by SupaflyFPV** [comment]
> I have some real life pics with Axis hardware, I could add them when I'm home

ok cool...I have one too lets see what you got....

Flipmode Red Axis Motors

**Comment by SupaflyFPV** [comment]
> image

Added the light mode logo - how do we set it up to change?

**Comment by VitroidFPV** [comment]
I have these





We can decide which photo to add or not... @SupaflyFPV I think it would be nice to mention the new Bando motors, to show that they work with devs to make cool stuff

**Comment by SupaflyFPV** [comment]
> I have these
> 
> We can decide which photo to add or not... @SupaflyFPV I think it would be nice to mention the new Bando motors, to show that they work with devs to make cool stuff

ok cool I can update it with forthcoming pics of the new Bando motors...the option I think is to use their product shots or to feature our 'developer' builds using their motors...?

**Comment by sugaarK** [comment]
is this ready to go @SupaflyFPV

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — DISMISSED** [review]

**Comment by SupaflyFPV** [comment]
I got some pics of the new motor - do you guys prefer this or the Axis product shots?

Screenshot 2023-12-15 at 01 52 37

**Comment by sugaarK** [comment]
> I got some pics of the new motor - do you guys prefer this or the Axis product shots?
> 
> Screenshot 2023-12-15 at 01 52 37

They look good

**Comment by SupaflyFPV** [comment]
ok check this out, if you're happy with it I think we're done...I tweaked the text and pics. 

@nerdCopter 
@VitroidFPV 
@haslinghuis 

With regard to Supafly self-promotion - if anyone is concerned about it always let me know (any occasion). Whenever I'm doing this stuff I have my Betaflight hat on. Any cross-over stuff (pics/mentions) I can take it or leave it so whatever is appropriate we go with. 👌

**Comment by nerdCopter** [comment]
thus far, each sponsor has a logo, a stock image, and a pilot image.  IMHO, i would prefer this image in the center, and a pilot image on the right.  maybe the pilot image can be a collage of the two images you presented.

center: 
image

right: the pink/blue one.

**Comment by nerdCopter** [comment]
also, light-mode looks a bit too light of a gray, maybe
image

**Comment by sugaarK** [comment]
> ok check this out, if you're happy with it I think we're done...I tweaked the text and pics.
> 
> @nerdCopter @VitroidFPV @haslinghuis
> 
> With regard to Supafly self-promotion - if anyone is concerned about it always let me know (any occasion). Whenever I'm doing this stuff I have my Betaflight hat on. Any cross-over stuff (pics/mentions) I can take it or leave it so whatever is appropriate we go with. 👌

im ok with the self promotion

**Comment by SupaflyFPV** [comment]
> also, light-mode looks a bit too light of a gray, maybe image

Ah so I don't know how to switch the logo file for the light/dark themes...anyone got advice on this? Both light and dark files are in there...

So shall we stick with product and dev pic for the protocol or leave as is?

**Comment by SupaflyFPV** [comment]
....this is dragging on a bit would be good to get it sorted...

**Review by haslinghuis — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Comment by haslinghuis** [comment]
@SupaflyFPV cannot see the conflicts - please rebase and fix.

**Comment by nerdCopter** [comment]
to be clear, this mockup is what i think it should be:
image

**Comment by SupaflyFPV** [comment]
> to be clear, this mockup is what i think it should be: image

yeah thats what Ive done

**Pull request closed without merging**
