### PR TITLE
Fix: File and Title Case checks

### PR DESCRIPTION
**Pull request by VitroidFPV**

### CODE REVIEW

**Comment by VitroidFPV** [comment]
Needs some touch-ups

**Comment by nerdCopter** [comment]
- performs as expected after some testing/feedback.
- forces author to use `Title Case` for headers.

**Comment by VitroidFPV** [comment]
I am open to making it a warning, not an error. I like having the consistency of everything across multiple projects that center around content authoring, but it can get in the way if the author isn't used to it

**Review by ctzsnooze — DISMISSED** [review]

**Comment by ctzsnooze** [comment]
For testing I changed the extension of magnetometer to .mdx and made no other changes, then attempted to commit.  The commit was blocked.  Log below.  

It seems that 'prettier' wanted to write changes, but was unable to do so:

```
[STARTED] Preparing lint-staged...
[COMPLETED] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc — 1 file
[STARTED] **/*.{tsx,js} — 0 files
[STARTED] **/*.{html,md,mdx,less,css,json} — 1 file
[STARTED] **/*.mdx — 1 file
[STARTED] tools/team_generation.mjs — 0 files
[SKIPPED] **/*.{tsx,js} — no files
[SKIPPED] tools/team_generation.mjs — no files
[STARTED] prettier --write --ignore-unknown
[STARTED] node tools/check_file_names.mjs
[COMPLETED] node tools/check_file_names.mjs
[STARTED] node tools/check_title_case.mjs
[FAILED] node tools/check_title_case.mjs [FAILED]
[FAILED] node tools/check_title_case.mjs [FAILED]
[COMPLETED] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[FAILED] prettier --write --ignore-unknown [KILLED]
[FAILED] prettier --write --ignore-unknown [KILLED]
[COMPLETED] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[COMPLETED] Cleaning up temporary files...

✖ node tools/check_title_case.mjs:
What is a Magnetometer? {#magnetometer-explanation} -> What Is a Magnetometer? {#Magnetometer-Explanation}
/Users/chris/Documents/Personal/RC/betaflight.com/docs/wiki/guides/current/Magnetometer.mdx:46

Setting local declination in the CLI -> Setting Local Declination in the CLI
/Users/chris/Documents/Personal/RC/betaflight.com/docs/wiki/guides/current/Magnetometer.mdx:101

Checking Magnetometer Orientation using Configurator's Sensors Tab -> Checking Magnetometer Orientation Using Configurator's Sensors Tab
/Users/chris/Documents/Personal/RC/betaflight.com/docs/wiki/guides/current/Magnetometer.mdx:189

Single-axis calibration -> Single-Axis Calibration
/Users/chris/Documents/Personal/RC/betaflight.com/docs/wiki/guides/current/Magnetometer.mdx:335

Validating the Heading using a mobile phone. -> Validating the Heading Using a Mobile Phone.
/Users/chris/Documents/Personal/RC/betaflight.com/docs/wiki/guides/current/Magnetometer.mdx:347

Fine-tuning Calibration in Sensors Tab. -> Fine-Tuning Calibration in Sensors Tab.
/Users/chris/Documents/Personal/RC/betaflight.com/docs/wiki/guides/current/Magnetometer.mdx:351

Where is heading information displayed? -> Where Is Heading Information Displayed?
/Users/chris/Documents/Personal/RC/betaflight.com/docs/wiki/guides/current/Magnetometer.mdx:357


✖ prettier --write --ignore-unknown failed without output (KILLED).
husky - pre-commit hook exited with code 1 (error)
```

I personally would not have capitalised everything quite in the same way, but I would have accepted most of the recommendations.  

Main thing is to fix the failure to write the changes.

**Comment by nerdCopter** [comment]
@VitroidFPV , if you make it `warning-only`, will it commit, or ask [Y/N] to commit?

**Comment by VitroidFPV** [comment]
@ctzsnooze 
> Main thing is to fix the failure to write the changes.

The check is just that. A check - it doesn't write anything, just logs the headers that need to be fixed, and how to fix them. I was aiming only to fix the existing code which did that.

That output of the commit command is expected for this case

**Comment by ctzsnooze** [comment]
Now I understand that this is a block that applies to `.mdx` files, but not to `.md` files, which prevents the commit from being applied until the 'suggested' changes are made.  

In practice, this means that the 'suggested' changes are actually mandatory, "must comply with" changes, since otherwise the commit cannot proceed.

The only alternative is to bypass the check with the `--no-verify` flag, or simply not use the .mdx extension.  But then any subsequent editing of the file, or anyone using .mdx later, will get forced to use this specific capitalisation, with no exceptions.

I don't think we've had any discussion about whether or not we actually want to enforce filename and heading capitalisation in this manner to every level of heading in every document.

While I do appreciate consistency, I am not in favour of all the automated suggestions, especially in lower level headings.  I do agree that the first level heading should be capitalised. 

Enforcing filename consistency makes sense, I guess, but then we should go through all the old files and name them with capitals.

Enforcing heading capitalisation is OK for the H1 heading, but gets a bit much on the lower level headings, some of which are quite lengthy series of words.

Perhaps the Capitalisation script could provide some more user-friendly advice than the current format, eg say something like:

```
The commit failed because some Headings or File Names were not Capitalised. Please make them match the proposed text exactly, and then try again. Or, to bypass this check, commit with the --no-verify flag.”
```

And maybe we can apply the mandatory check only to first level headings, and perhaps draft a 'style guide' with examples of good capitalisation and link practices, for example, in the mdx reference document.

**Comment by nerdCopter** [comment]
i think this PR is good.  those with GUI-based git environments may think otherwise.

results of testing .md to .mdx , then .mdx to .md:
```
$ git mv ./docs/development/Mixer.md ./docs/development/Mixer.mdx
## fix-checks
R  docs/development/Mixer.md -> docs/development/Mixer.mdx

$ git add -u ; git commit -m "tesing PR 339"
npm WARN exec The following package was not found and will be installed: lint-staged@15.2.2
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
[fix-checks efd6c2c78] tesing PR 339
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename docs/development/{Mixer.md => Mixer.mdx} (100%)
## fix-checks

$ git mv ./docs/development/Atomic-Barrier.md ./docs/development/Atomic-Barrier.mdx
## fix-checks
R  docs/development/Atomic-Barrier.md -> docs/development/Atomic-Barrier.mdx

$ git add -u ; git commit -m "tesing PR 339"
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ .lintstagedrc — 1 file
    ↓ **/*.{tsx,js} — no files
    ❯ **/*.{html,md,mdx,less,css,json} — 1 file
      ✖ prettier --write --ignore-unknown [KILLED]
    ❯ **/*.mdx — 1 file
      ✔ node tools/check_file_names.mjs
      ✖ node tools/check_title_case.mjs [FAILED]
    ↓ tools/team_generation.mjs — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ node tools/check_title_case.mjs:
This commit would fail because some headings were not properly capitalized following the title case format. Use the proposed changes or make your own, and then try again. Or, commit with the --no-verify flag to bypass this check entirely:

Atomic Barrier implementation -> Atomic Barrier Implementation
/media/disk2/SYNC/nerdCopter-GIT/betaflight.com/docs/development/Atomic-Barrier.mdx:1

(possibly markme address load) -> (Possibly Markme Address Load)
/media/disk2/SYNC/nerdCopter-GIT/betaflight.com/docs/development/Atomic-Barrier.mdx:70

barier (markme) start -> Barier (Markme) Start
/media/disk2/SYNC/nerdCopter-GIT/betaflight.com/docs/development/Atomic-Barrier.mdx:71

(increment markme, load and store to memory) -> (Increment Markme, Load and Store to Memory)
/media/disk2/SYNC/nerdCopter-GIT/betaflight.com/docs/development/Atomic-Barrier.mdx:73

barier(markme)  end -> Barier(markme)  End
/media/disk2/SYNC/nerdCopter-GIT/betaflight.com/docs/development/Atomic-Barrier.mdx:78

(markme value should be cached in register on next increment) -> (Markme Value Should Be Cached in Register on Next Increment)
/media/disk2/SYNC/nerdCopter-GIT/betaflight.com/docs/development/Atomic-Barrier.mdx:81


✖ prettier --write --ignore-unknown failed without output (KILLED).
husky - pre-commit hook exited with code 1 (error)
## fix-checks
R  docs/development/Atomic-Barrier.md -> docs/development/Atomic-Barrier.mdx
```

all warnings expected

**Comment by nerdCopter** [comment]
on the subject of if CamelCase should be required, i leave that to everyone else's opinion.

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
