### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by PictureElement**
1. Improve **Latest News** section on the homepage. 
- Articles are displayed as cards.
- Article preview images are displayed in a 4:3 aspect ratio and they will fill the height and width of the box. 
2. Improve **About** section on the homepage.
- Accordion style content.
3. Make some paragraphs stand out by adding the .lead class.

### CODE REVIEW

**Comment by mikeller** [comment]
@PictureElement: Thanks for helping with this. Unfortunately we do not have an easy way to deploy changes to a staging environment. For this reason, can you please provide some screenshots with a preview of your changes?

**Comment by PictureElement** [comment]
@mikeller You're welcome; it has been my pleasure helping YOU out!

**Comment by PictureElement** [comment]
@mikeller Here are the screenshots you've requested. Please let me know if I can help in any Front-end related issue.

about-section-1
about-section-2
latest-news-section
supportive-text

**Review by mikeller — APPROVED** [review]

**Comment by PictureElement** [comment]
Hello @mikeller. I think betaflight.com needs improvements, and I would like to help. Since I am about to start learning Gatsby in my spare time, What do you think about developing betaflight.com on the platform?

**Pull request merged**
