### PR TITLE
Remove unified target creation

### PR DESCRIPTION
**Pull request by haslinghuis**
- BF uses define based configuration management.
- Unified target submission has been deprecated.

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
maybe "archive" section rather than removal?

**Review by VitroidFPV — APPROVED** [review]

**Comment by VitroidFPV** [comment]
I'm both for archival or removal - IMO pages that are archived should still be somewhat relevant in the future, no one will likely ever be making a unified target nowadays

**Comment by sugaarK** [comment]
@blckmn thoughts ?

**Comment by blckmn** [comment]
Yeah looks ok to me , do we have an equivalent doc for the config files?

**Review by blckmn — APPROVED** [review]

**Comment by haslinghuis** [comment]
https://betaflight.com/docs/development/manufacturer/creating-configuration

**Pull request merged**
