### PR TITLE
Add GitHub username links

### PR DESCRIPTION
**Pull request by atomgomba**
By adding this configuration, the markdown processor will convert `@username` mentions into clickable links that point to the GitHub user profiles.

### CODE REVIEW

**Comment by atomgomba** [comment]
This is just an example. I didn't want to edit all the mentions before making an agreement that this function is needed.
image

**Review by haslinghuis — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Comment by haslinghuis** [comment]
@atomgomba please rebase and resolve conflicts.

**Review by haslinghuis — APPROVED** [review]

**Comment by ctzsnooze** [comment]
great idea, thank you!

**Review by ctzsnooze — APPROVED** [review]

**Comment by ctzsnooze** [comment]
Use
`npm install remark-mentions`
to build locally

**Comment by nerdCopter** [comment]
> Use `npm install remark-mentions` to build locally

it's in package.json, so standard `yarn install` should do it.

**Pull request merged**
